config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get "address/index"
  get "address/new"
  get "address/edit"
  get "address/create"
  get "address/update"
  get "address/destroy"
  # get 'cart/index'
  # get 'cart/create'
  resources :cart
  # post 'cart/create', to: 'cart#create', as: 'cart_create'
  get "orders/confirm", to: "orders#confirm", as: "confirm"
  resources :orders
  # resources :orders, only => [:new, :confirm, :create, :destroy, :index, :cart]

  # , only: [:index, :create, :destroy, :show] do     #⇒（従来のnewアクションを削除）
  #   get :cart, on: :collection        #⇒（getメソッドに基づく、cartアクションのルートを追加）
  #   put :new, on: :collection         #⇒（PUTメソッドに基づく、newアクションのルートを追加）
  # end
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  attr_accessor :address_number
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def cart
  end

  def new
    @order = Order.new
    @addresses = current_user.addresses.all
    # render "confirm"
  end

  def confirm
    @order = Order.new(order_params)
    # @orderはでかい箱で、その中に小さい箱を指定するためにストロングパラメーターを指定している。

    # if文を記述して、hidden fieldが作動するようにする。
    # ご自身の住所と配送先住所が選択された場合はhiddenで処理

    # 現在memberに登録されている住所であれば
    if params[:order][:address_option] == "0"
      @addresses = current_user.addresses
      @order.order_address = @addresses[0].address
      @order.order_name = @addresses[0].address_name
      # collection.selectであれば
    elsif params[:order][:address_option] == "1"
      ship = Address.find(params[:order][:user_id])
      @order.order_address = ship.address
      @order.order_name = ship.address_name

      # 新規住所入力であれば
    elsif params[:order][:address_option] = "2"
      @order.order_address = params[:order][:order_address]
      @order.order_name = params[:order][:order_name]
    else
      render "new"
    end

    @cart_items = current_user.cart_items.all
    @order.user_id = current_user.id
  end

  # 注文情報保存
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.save
    # ordered_itmemの保存
    current_user.cart_items.each do |cart_item| #カートの商品を1つずつ取り出しループ
      @order_item = OrderItem.new #初期化宣言
      @order_item.product_id = cart_item.product_id
      @order_item.order_id = @order.id
      @order_item.order_quantity = cart_item.quantity
      # 購入が完了したらカート情報は削除するのでこちらに保存します
      @order_item.order_price = (cart_item.product.unit_price * 1.08).floor
      @order_item.save #注文商品を保存
    end #ループ終わり

    current_user.cart_items.destroy_all #カートの中身を削除
    redirect_to cart_index_path
  end

  def destroy
  end

  def index
  end

  private

  def order_params
    params.require(:order).permit(:postage, :payment_method, :order_name, :order_address, :user_id, :total_price, :status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/orders/cart.html.erb
<h1><%= t("title.choose_products") %></h1>

<%= form_with(scope: nil, local: true, url: orders_path, method: :put) do |form|%>
  <table>
    <thead>
      <tr>
        <th><%= t("column.product_number") %></th>
        <th><%= t("column.product_name") %></th>
        <th><%= t("column.unit_price") %></th>
        <th><%= t("column.image") %></th>
        <th><%= t("column.description") %></th>
        <th><%= t("column.check") %></th>
        <th><%= t("column.quantity") %></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each_with_index do |product, idx| %>
        <tr>
          <td><%= product.number %></td>
          <td><%= product.name %></td>
          <td  class="right_shift"><%= number_with_delimiter product.unit_price.round %></td>
          <% if product.image.present? %>%
            <td><%= image_tag product.image.url %></td>
          <% else %>
            <td><%= image_tag "default_product.png" %></td>
          <% end %>
          <td><%= product.description %></td>
          <td><%= check_box_tag "orders[#{idx}][product]", product.id %></td>
          <td><%= number_field_tag "orders[#{idx}][quantity]", 1, class: "small_field" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= form.submit t("button.go_order") %>
<% end %>

app/views/orders/confirm.html.erb
<div "container">
    <div class='row mb-3'>
        <div class='col-8 offset-1'>
          <h4 class="pt-3">注文情報確認</h4>
        </div>
    </div>
    <div class='row'>
        <div class='col-7 offset-1'>
          <table class='table table-bordered border-dark'>
            <tr class="table-secondary">
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
            </tr>
            <!--合計金額totalの初期化-->
            <% total = 0 %>
            <% @cart_items.each do |cart_item| %>
              <tr>
                  <td><%= cart_item.product.name %></td>
                  <td><%= (cart_item.product.unit_price*1.08).to_i %></td>
                  <td><%= cart_item.quantity %></td>
                  <td>
                      <!--小計の計算-->
                      <% subtotal = ((cart_item.product.unit_price*cart_item.quantity)*1.08).to_i %>
                      <!--小計を表示-->
                      <%= subtotal %>
                  </td>
              </tr>
              <!--アイテムごとに合計金額に加算する-->
              <% total += (cart_item.product.unit_price*cart_item.quantity)*1.08 %>
            <% end %>
          </table>
        </div>
        <div class='col-3'>
            <table class="table table-bordered border-dark">
                <% @order.postage = 800 %>
                <tr><th class="table-secondary">送料</th><td><%= @order.postage %></td></tr>
                <tr><th class="table-secondary">商品合計</th><td><%= total.to_i %></td></tr>
                <% @order.total_price = @order.postage + total.to_i %>
                <tr><th class="table-secondary">請求金額</th><td><%= @order.total_price %></td></tr>
            </table>
        </div>
    </div>

    <div class="row">
        <div class='col-11 offset-1'>
            <table class="table table-borderless">
                <tr><th class="col-1">支払い方法</th><td class="col-10"><%= @order.payment_method %></td></tr>
                <tr><th class="col-1">お届け先</th><td class="col-10">
                <%= @order.order_address %>
                <%= @order.order_name %>
                </td></tr>
            </table>
        </div>
    </div>

    <div class="row justify-content-center">
        <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
                            <%= render 'error_messages', object: f.object %>
            <%= f.hidden_field :user_id %>
            <%= f.hidden_field :postage %>
            <%= f.hidden_field :total_price %>
            <%= f.hidden_field :payment_method %>
            <%= f.hidden_field :order_name %>
            <%= f.hidden_field :order_address %>
            <%= f.hidden_field :status %>
            <%= f.submit "注文を確定する", class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
    <div class="row py-2">
        <div class="col-10 offset-2">
            <h4>注文情報入力</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <%= form_with model: @order, url: 'confirm', method: :get, local: true do |f| %>
                <h5 class="font-weight-bold">支払い方法</h5>
                <p>
                <%= f.radio_button :payment_method,:クレジットカード,  checked: "checked" %>
                <%= f.label :payment_method, "クレジットカード" %>
                <br>
                <%= f.radio_button :payment_method, :銀行振込 %>
                <%= f.label :payment_method, "銀行振込" %>
                </p>
                <h5 class="font-weight-bold">お届け先</h5>

                    <%= f.radio_button :address_option, 0, checked: "checked" %>
                    <%= f.label :order_address, "ご自身の住所" %>
                <br>
                    <%= current_user.address %>
                    <%= current_user.name %>
                <br>
                    <%= f.radio_button :address_option, 1 %>
                    <%= f.label :order_address, "登録済住所から選択" %>
                <br>
                    <%= f.collection_select :user_id, @addresses, :id, :address %>
                <br>
                    <%= f.radio_button :address_option, 2 %>
                    <%= f.label :order_address, "新しいお届け先" %>
                <table>
                    <tr>
                        <td class='col-3'><%= f.label :order_address, "住所" %></td>
                        <td class='col-9'><%= f.text_field :order_address, :placeholder => "東京都渋谷区代々木", class: "w-100" %></td>
                    </tr>
                    <tr>
                        <td class='col-3'><%= f.label :order_name, "宛名" %></td>
                        <td class='col-9'><%= f.text_field :order_name, :placeholder => "山田花子" %></td>
                    </tr>
                </table>
                    <div class="row justify-content-center py-5">
                        <%= f.submit "確認画面へ進む" , class:"btn btn-primary" %>
                    </div>
                <% end %>
        </div>
    </div>

</div>