config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get "address/index"
  get "address/new"
  get "address/edit"
  get "address/create"
  get "address/update"
  get "address/destroy"
  # get 'cart/index'
  # get 'cart/create'
  resources :cart
  # post 'cart/create', to: 'cart#create', as: 'cart_create'
  get "orders/confirm", to: "orders#confirm", as: "confirm"
  resources :orders
  # resources :orders, only => [:new, :confirm, :create, :destroy, :index, :cart]

  # , only: [:index, :create, :destroy, :show] do     #⇒（従来のnewアクションを削除）
  #   get :cart, on: :collection        #⇒（getメソッドに基づく、cartアクションのルートを追加）
  #   put :new, on: :collection         #⇒（PUTメソッドに基づく、newアクションのルートを追加）
  # end
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :cart_item
  has_many :order, through: :order_item
  validates :name, presence: true
  validates :number, presence: true

  def taxin_price
    unit_price * 1.1
  end

  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }
enum payment_method: ["クレジットカード", "銀行振込"]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:number, :name, :unit_price, :image, :description, :quantity, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit_price, style: "display: block" %>
    <%= form.text_field :unit_price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Number:</strong>
    <%= product.number %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Unit price:</strong>
    <%= product.unit_price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= product.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

    <strong>Quantity:</strong>
    <%= number_with_precision(product.quantity,precision: 0,strip_insignificant_zeros: true) %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<%= react_component("Product", { products: @products }) %>

<%= link_to "新規追加", new_product_path %>
<div>
  <%= link_to "ログアウト", sign_out_path, method: :delete %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>